// this jobTitles used at recruiter side to find candidate feature
export const jobTitles = [
    // Software & IT
    "Software Engineer",
    "React Developer",
    "Java Developer",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Data Scientist",
    "Machine Learning Engineer",
    "AI Engineer",
    "Cybersecurity Analyst",
    "DevOps Engineer",
    "Cloud Engineer",
    "Database Administrator",
    "Blockchain Developer",
    "Game Developer",
    "Embedded Systems Engineer",
    "Mobile App Developer",
  
    // Product & Management
    "Product Manager",
    "Project Manager",
    "Business Analyst",
    "Scrum Master",
    "Operations Manager",
    "Risk Manager",
    "Supply Chain Manager",
  
    // Sales & Marketing
    "Marketing Manager",
    "Sales Executive",
    "Digital Marketing Specialist",
    "SEO Analyst",
    "Social Media Manager",
    "Brand Manager",
    "Public Relations Specialist",
  
    // HR & Administration
    "Human Resources Manager",
    "Recruiter",
    "Training and Development Manager",
    "Administrative Officer",
  
    // Finance & Banking
    "Financial Analyst",
    "Investment Banker",
    "Accountant",
    "Auditor",
    "Tax Consultant",
    "Actuary",
    "Loan Officer",
  
    // Engineering
    "Civil Engineer",
    "Mechanical Engineer",
    "Electrical Engineer",
    "Automobile Engineer",
    "Aerospace Engineer",
    "Chemical Engineer",
    "Biomedical Engineer",
    "Structural Engineer",
  
    // Healthcare & Medicine
    "Doctor",
    "Nurse",
    "Pharmacist",
    "Dentist",
    "Physiotherapist",
    "Radiologist",
    "Veterinarian",
    "Surgeon",
  
    // Legal & Law
    "Lawyer",
    "Judge",
    "Paralegal",
    "Legal Advisor",
  
    // Education & Research
    "Teacher",
    "Professor",
    "Research Scientist",
    "Librarian",
    "Academic Counselor",
  
    // Creative & Media
    "Graphic Designer",
    "UI/UX Designer",
    "Content Writer",
    "Journalist",
    "Video Editor",
    "Animator",
    "Art Director",
    "Photographer",
    "Filmmaker",
    "Fashion Designer",
    "Interior Designer",
    "Music Producer",
  
    // Hospitality & Tourism
    "Hotel Manager",
    "Event Planner",
    "Chef",
    "Tour Guide",
    "Travel Agent",
    "Flight Attendant",
  
    // Sports & Fitness
    "Athlete",
    "Fitness Trainer",
    "Sports Coach",
    "Physiotherapist",
  
    // Government & Public Sector
    "Police Officer",
    "Firefighter",
    "Military Officer",
    "Social Worker",
    "Diplomat",
  
    // Miscellaneous
    "Entrepreneur",
    "Freelancer",
    "Data Entry Operator",
    "Customer Support Representative",
  ];

// these location use to in home page to find job
export const allLocations = {
    "Andhra Pradesh": [
      "Visakhapatnam, Andhra Pradesh",
      "Vijayawada, Andhra Pradesh",
      "Guntur, Andhra Pradesh",
    ],
    "Arunachal Pradesh": [
      "Itanagar, Arunachal Pradesh",
      "Tawang, Arunachal Pradesh",
      "Pasighat, Arunachal Pradesh",
    ],
    Assam: ["Guwahati, Assam", "Silchar, Assam", "Dibrugarh, Assam"],
    Bihar: ["Patna, Bihar", "Gaya, Bihar", "Bhagalpur, Bihar"],
    Chhattisgarh: [
      "Raipur, Chhattisgarh",
      "Bilaspur, Chhattisgarh",
      "Durg, Chhattisgarh",
    ],
    Delhi: ["New Delhi, Delhi", "Rohini, Delhi", "Dwarka, Delhi"],
    Goa: ["Panaji, Goa", "Margao, Goa", "Vasco da Gama, Goa"],
    Gujarat: ["Ahmedabad, Gujarat", "Surat, Gujarat", "Vadodara, Gujarat"],
    Haryana: ["Gurugram, Haryana", "Faridabad, Haryana", "Karnal, Haryana"],
    "Himachal Pradesh": [
      "Shimla, Himachal Pradesh",
      "Manali, Himachal Pradesh",
      "Dharamshala, Himachal Pradesh",
    ],
    Jharkhand: [
      "Ranchi, Jharkhand",
      "Jamshedpur, Jharkhand",
      "Dhanbad, Jharkhand",
    ],
    "Jammu and Kashmir": [
      "Srinagar, Jammu and Kashmir",
      "Jammu, Jammu and Kashmir",
      "Anantnag, Jammu and Kashmir",
    ],
    Karnataka: [
      "Bengaluru, Karnataka",
      "Mysuru, Karnataka",
      "Hubli, Karnataka",
    ],
    Kerala: [
      "Thiruvananthapuram, Kerala",
      "Kochi, Kerala",
      "Kozhikode, Kerala",
    ],
    Ladakh: ["Leh, Ladakh", "Kargil, Ladakh"],
    "Madhya Pradesh": [
      "Bhopal, Madhya Pradesh",
      "Indore, Madhya Pradesh",
      "Gwalior, Madhya Pradesh",
    ],
    Maharashtra: [
      "Mumbai, Maharashtra",
      "Pune, Maharashtra",
      "Nagpur, Maharashtra",
    ],
    Manipur: ["Imphal, Manipur", "Bishnupur, Manipur", "Thoubal, Manipur"],
    Meghalaya: ["Shillong, Meghalaya", "Tura, Meghalaya", "Jowai, Meghalaya"],
    Mizoram: ["Aizawl, Mizoram", "Lunglei, Mizoram", "Champhai, Mizoram"],
    Nagaland: ["Kohima, Nagaland", "Dimapur, Nagaland", "Mokokchung, Nagaland"],
    Odisha: ["Bhubaneswar, Odisha", "Cuttack, Odisha", "Rourkela, Odisha"],
    Punjab: ["Ludhiana, Punjab", "Amritsar, Punjab", "Jalandhar, Punjab"],
    Rajasthan: ["Alwar, Rajasthan", "Jaipur, Rajasthan", "Udaipur, Rajasthan"],
    Sikkim: ["Gangtok, Sikkim", "Namchi, Sikkim", "Gyalshing, Sikkim"],
    "Tamil Nadu": [
      "Chennai, Tamil Nadu",
      "Coimbatore, Tamil Nadu",
      "Madurai, Tamil Nadu",
    ],
    Telangana: [
"Adilabad",
"Adilabad Rural",  
"Adilabad Urban",  
"Bazarhatnoor",  
"Bela",  
"Bheempur",  
"Boath",  
"Gadiguda",  
"Gudihatnoor",  
"Ichoda",  
"Inderavelly",  
"Jainath",  
"Mavala",  
"Narnoor",  
"Neradigonda",  
"Sirikonda",  
"Talamadugu",  
"Tamsi",  
"Utnoor",  

"Bhadradri Kothagudem",
"Allapalli",  
"Annapureddypalli",  
"Aswapuram",  
"Aswaraopeta",  
"Bhadrachalam",  
"Burgampahad",  
"Chandrugonda",  
"Cherla",  
"Chunchupalli",  
"Dammapeta",  
"Dummugudem",  
"Gundala",  
"Julurupadu",  
"Karakagudem",  
"Kothagudem",  
"Laxmidevipalli",  
"Manugur",  
"Mulakalapally",  
"Palwancha",  
"Pinapaka",  
"Sujathanagar",  
"Tekulapally",  
"Yellandu",  

"Hanumakonda",
"Atmakur",  
"Bheemadevarapalli",  
"Damera",  
"Dharmasagar",  
"Elkathurthi",  
"Hanamkonda",  
"Hasanparthy",  
"Inavole",  
"Kamalapur",  
"Khazipet",  
"Nadikuda",  
"Parkal",  
"Shayampet",  
"Velair",  

"Hyderabad",
"Amberpet",  
"Ameerpet",  
"Asifnagar",  
"Bahadurpura",  
"Bandlaguda",  
"Charminar",  
"Golconda",  
"Himayathnagar",  
"Khairthabad",  
"Marredpally",  
"Musheerabad",  
"Nampally",  
"Saidabad",  
"Secunderabad",  
"Shaikpet",  
"Tirumalgiri",  
"Tirumalagiry",

"Jagitial",  
"Beerpur",  
"Buggaram",  
"Dharmapuri",  
"Gollapalli",  
"Ibrahimpatnam",  
"Jagitial Rural",  
"Jagtial",  
"Kathalapur",  
"Kodimial",  
"Korutla",  
"Mallapur",  
"Mallial",  
"Medipalli",  
"Metpalli",  
"Pegadapalli",  
"Raikal",  
"Sarangapur",  
"Velgatoor",

"Jangoan",
"Bachannapeta",  
"Chilpur",  
"Devaruppula",  
"Ghanpur (Station)",  
"Jangaon",  
"Kodakandla",  
"Lingalaghanpur",  
"Narmetta",  
"Palakurthi",  
"Raghunathpalle",  
"Tharigoppula",  
"Zaffergadh",

"Jayashankar Bhupalapally",
"Bhupalpalle",  
"Chityal",  
"Ghanapur (Mulug)",  
"Kataram",  
"Mahadevpur",  
"Malhar Rao",  
"Mogullapalle",  
"Mutharam (Mahadevpur)",  
"Palimela",  
"Regonda",  
"Tekumatla",

"Jogulamba Gadwal",  
"Alampur",
"Dharur",
"Gadwal",
"Ghattu",
"Ieeja",
"Itikyal",
"Kaloor Thimmandoddi",
"Maldakal",
"Manopadu",
"Rajoli",
"Undavelly",
"Waddepalle",
"Waddepally",

"Kamareddy",
"Banswada",
"Bhiknur",
"Bibipet",
"Bichkunda",
"Birkoor",
"Domakonda",
"Gandhari",
"Jukkal",
"Kamareddy",
"Lingampet",
"Machareddy",
"Madnur",
"Nagireddypet",
"Nasurullabad",
"Nizamsagar",
"Pedda Kodapgal",
"Pitlam",
"Rajampet",
"Ramareddy",
"Sadasivanagar",
"Tadwai",
"Yellareddy",

"Karimnagar",
"Chigurumamidi",
"Choppadandi",
"Ellandakunta",
"Gangadhara",
"Ganneruvaram",
"Huzurabad",
"Jammikunta",
"Karimnagar",
"Karimnagar Rural",
"Kothapally",
"Manakondur",
"Ramadugu",
"Shankarapatnam",
"Thimmapur LMD",
"V. Saidapur",
"Veenavanka",

"Khammam",
"Bonakal",
"Chinthakani",
"Enkoor",
"Kalluru",
"Kallur",
"Kamepalli",
"Kamepally",
"Khammam (Rural)",
"Khammam (Urban)",
"Konijerla",
"Kusumanchi",
"Madhira",
"Mudigonda",
"Nelakondapalli",
"Nelakondapally",
"Penuballi",
"Penubally",
"Raghunadhapalem",
"Sathupalli",
"Sathupally",
"Singareni",
"Thallada",
"Tirumalayapalem",
"Thirumalayapalem",
"Vemsoor",
"Wyra",
"Yerrupalem",

"Kumuram Bheem Asifabad",
"Asifabad",  
"Bejjur",  
"Chintalamanepally",  
"Dahegaon",  
"Jainoor",  
"Kagaznagar",  
"Kerameri",  
"Kouthala",  
"Lingapur",  
"Penchicalpet",  
"Rebbena",  
"Sirpur (T)",  
"Sirpur (U)",  
"Tiryani",  
"Wankidi",  

"Mahabubabad",
"Bayyaram",  
"Chinnagudur",  
"Danthalapalle",  
"Dornakal",  
"Gangaram",  
"Garla",  
"Gudur",  
"Kesamudram",  
"Kothagudem",  
"Kuravi",  
"Mahbubabad",  
"Maripeda",  
"Nallikudur",  
"Narsimhulapet",  
"Peddavangara",  
"Thorrur",  

"Mahabubnagar",
"Addakal",  
"Balanagar",  
"Bhoothpur",  
"Chinnachintakunta",  
"Devarakadara",  
"Gandeed",  
"Hanwada",  
"Jadcherla",  
"Koilkonda",  
"Mahabubnagar Urban",  
"Mahbubnagar Rural",  
"Midjil",  
"Mohammadabad",  
"Moosapet",  
"Nawabpet",  
"Rajapur",  

"Mancherial",
"Bellampally",  
"Bheemaram",  
"Bheemini",  
"Chennur",  
"Dandepally",  
"Hajipur",  
"Jaipur",  
"Jannaram",  
"Kannepally",  
"Kasipet",  
"Kotapally",  
"Luxettipet",  
"Mancherial",  
"Mandamarri",  
"Naspur",  
"Nennel",  
"Tandur",  
"Vemanpally",  

"Medak",
"Alladurg",  
"Chegunta",  
"Chilpched",  
"Havelighanapur",  
"Kowdipalli",  
"Kulcharam",  
"Manoharabad",  
"Masaipet",  
"Medak",  
"Narsapur",  
"Narsingi",  
"Nizampet",  
"Papannapet",  
"Ramayampet",  
"Regode",  
"Shankarampet [A]",  
"Shankarampet [R]",  
"Shivampet",  
"Tekmal",  
"Tupran",  
"Yeldurthy",  

"Medchal Malkajgiri",
"Alwal",
"Bachupally",
"Balanagar",
"Dundigal Gandimaisamma",
"Gandimaisamma Dundigal",
"Ghatkesar",
"Kapra",
"Keesara",
"Kukatpally",
"Malkajgiri",
"Medchal",
"Medipally",
"Muduchinthalapally",
"Quthbullapur",
"Qutballapur",
"Shamirpet",
"Uppal",

"Mulugu",
"Eturnagaram",
"Govindaraopet",
"Kannaigudem",
"Mangapet",
"Mulug",
"Tadvai",
"Venkatapur",
"Venkatapuram",
"Wajedu",
"Wazeed",

"Nagarkurnool",
"Achampeta",
"Amrabad",
"Balmoor",
"Bijinapalle",
"Charakonda",
"Kalwakurthy",
"Kodair",
"Kollapur",
"Lingal",
"Nagarkurnool",
"Padara",
"Peddakothapalle",
"Pentlavelli",
"Tadoor",
"Telkapalle",
"Thimmajipeta",
"Uppununthala",
"Urkonda",
"Vangoor",
"Veldanda",

"Nalgonda",
"Adavidevulapalli",
"Anumula",
"Chandampet",
"Chandur",
"Chintha Pally",
"Chityala",
"Dameracherla",
"Devarakonda",
"Gundlapally (Dindi)",
"Gurrampode",
"Kanagal",
"Kattangoor",
"Kethe Pally",
"Konda Mallepally",
"Madugulapally",
"Marriguda",
"Miryalaguda",
"Munugode",
"Nakrekal",
"Nalgonda",
"Nampally",
"Narketpally",
"Neredugommu",
"Nidamanoor",
"Pedda Adiserlapally",
"Peddavoora",
"Shali Gouraram",
"Thipparthi",
"Tirumalagiri Sagar",
"Tripuraram",
"Vemula Pally",

"Narayanpet",
"Damaragidda",
"Dhanwada",
"Kosgi",
"Krishna",
"Maddur",
"Maganoor",
"Makthal",
"Marikal",
"Narayanpet",
"Narva",
"Utkoor",

"Nirmal",
"Basar",
"Bhainsa",
"Dasturabad",
"Dilawarpur",
"Kaddam (Peddur)",
"Khanapur",
"Kubeer",
"Kuntala",
"Laxmanchanda",
"Lokeswaram",
"Mamda",
"Mudhole",
"Narsapur G",
"Nirmal",
"Nirmal Rural",
"Pembi",
"Sarangapur",
"Soan",
"Tanur",

"Nizamabad",
"Armur",
"Balkonda",
"Bheemgal",
"Bodhan",
"Chandur",
"Dharpalle",
"Dichpalle",
"Indalwai",
"Jakranpalle",
"Kammarapalle",
"Kotgiri",
"Makloor",
"Mendora",
"Mortad",
"Mosara",
"Mugpal",
"Mupkal",
"Nandipet",
"Navipet",
"Nizamabad North",
"Nizamabad Rural",
"Nizamabad South",
"Renjal",
"Rudrur",
"Sirkonda",
"Varni",
"Velpur",
"Yedapalle",
"Yergatla",

"Peddapalli",
"Anthergaon",
"Dharmaram",
"Eligaid",
"Julapalli",
"Kamanpur",
"Manthani",
"Mutharam (Manthani)",
"Odela",
"Palakurthy",
"Peddapalli",
"Ramagiri",
"Ramagundam",
"Srirampur",
"Sulthanabad",

"Rajanna Sircilla",
"Boinpalli",
"Chandurthi",
"Ellanthakunta",
"Gambhiraopet",
"Konaraopet",
"Mustabad",
"Rudrangi",
"Sircilla",
"Thangallapalli",
"Veernapalli",
"Vemulawada",
"Vemulawada Rural",
"Yellareddipet",

"Wanaparthy",
"Amarchintha",
"Amarachintha",
"Atmakur",
"Chinnambavi",
"Ghanpur",
"Gopalpeta",
"Kothakota",
"Madanapur",
"Pangal",
"Pebbair",
"Peddamandadi",
"Revally",
"Srirangapur",
"Wanaparthy",
"Weepangandla",

"Warangal",
"Chennaraopet",
"Duggondi",
"Geesugonda",
"Khanapur",
"Khila Warangal",
"Nalla Belli",
"Nallabelli",
"Narsampet",
"Nekkonda",
"Parvathagiri",
"Raiparthy",
"Rayaparthy",
"Sangem",
"Warangal",
"Wardhanna Pet",
"Wardhannapet",

"Yadadri Bhuvanagiri",
"Adda Guduru",
"Addaguduru",
"Alair",
"Atmakur (M)",
"Atmakur(M)",
"B Pochampally",
"B.Pochampally",
"Bhongir",
"Bibinagar",
"Bommalaramaram",
"Bommala Ramaram",
"Choutuppal",
"Gundala",
"Motakonduru",
"Mothkur",
"Narayanpur",
"Narayanapur",
"Rajapeta",
"Rajapet",
"Ramannapet",
"Ramannapeta",
"Thurkapally",
"Valigonda",
"Yadagirigutta",

"Ranga Reddy",
"Abdullapurmet",
"Amangal",
"Balapur",
"Chevella",
"Farooqnagar",
"Gandipet",
"Hayathnagar",
"Ibrahimpatnam",
"Jilled Chowdergudem",
"Kadthal",
"Kandukur",
"Keshampeta",
"Kondurg",
"Kothur",
"Madgul",
"Maheshwaram",
"Manchal",
"Moinabad",
"Nandigama",
"Rajendranagar",
"Saroornagar",
"Serilingampally",
"Shabad",
"Shamshabad",
"Shankarpally",
"Talakondapalle",
"Yacharam",

"Sangareddy",
"Ameenpur",
"Andole",
"Chowtakur",
"Gummadidala",
"Hathnoora",
"Jharasangam",
"Jinnaram",
"Kalher",
"Kandi",
"Kangti",
"Kohir",
"Kondapur",
"Manoor",
"Mogudampally",
"Munipally",
"Nagalgidda",
"Narayankhed",
"Nyalkal",
"Patancheru",
"Pulkal",
"Raikode",
"Ramchandrapuram",
"Sadasivpet",
"Sangareddy",
"Sirgapoor",
"Vatpally",
"Zahirabad",

"Siddipet",
"Akkannapet",
"Bejjanki",
"Cheriyal",
"Chinnakodur",
"Dhoolmitta",
"Doultabad",
"Dubbak",
"Gajwel",
"Husnabad",
"Jagdevpur",
"Koheda",
"Komuravelli",
"Kondapak",
"Maddur",
"Markook",
"Mirdoddi",
"Mulug",
"Nanganoor",
"Narayanaraopet",
"Raipole",
"Siddipet Rural",
"Siddipet Urban",
"Thoguta",
"Wargal",

"Suryapet",
"Ananthagiri",
"Atmakur (S)",
"Chilkur",
"Chinthalapalem Mallareddygudem",
"Chivvemla",
"Garide Pally",
"Huzurnagar",
"Jaji Reddi Gudem (Arvapally)",
"Kodad",
"Maddirala",
"Mattam Pally",
"Mella Chervu",
"Mothey",
"Munagala",
"Nadigudem",
"Nagaram",
"Nereducherla",
"Nuthankal",
"Palakeedu",
"Penpahad",
"Suryapet",
"Thirumalagiri",
"Thungathurthi",
"Thungaturthy",

"Vikarabad",
"Bantwaram",
"Basheerabad",
"Bomaraspeta",
"Bomraspeta",
"Chowdapur",
"Dharur",
"Doma",
"Doulathabad",
"Doulatabad",
"Kodangal",
"Kotepally",
"Kulkacharla",
"Marpalle",
"Marpally",
"Mominpet",
"Nawabpet",
"Pargi",
"Peddemul",
"Pudur",
"Tandur",
"Vikarabad",
"Yelal",
"Yalal",
    ],
    Tripura: ["Agartala, Tripura", "Udaipur, Tripura", "Kailashahar, Tripura"],
    "Uttar Pradesh": [
      "Noida, Uttar Pradesh",
      "Lucknow, Uttar Pradesh",
      "Kanpur, Uttar Pradesh",
    ],
    Uttarakhand: [
      "Dehradun, Uttarakhand",
      "Haridwar, Uttarakhand",
      "Nainital, Uttarakhand",
    ],
    "West Bengal": [
      "Kolkata, West Bengal",
      "Darjeeling, West Bengal",
      "Siliguri, West Bengal",
    ],

    // USA major cities locations
    Arizona: [
      "Phoenix, Arizona",
      "Tucson, Arizona",
      "Mesa, Arizona",
      "Scottsdale, Arizona",
      "Chandler, Arizona",
    ],
    California: [
      "Los Angeles, California",
      "San Francisco, California",
      "San Diego, California",
      "Sacramento, California",
      "San Jose, California",
    ],
    Florida: [
      "Miami, Florida",
      "Orlando, Florida",
      "Tampa, Florida",
      "Jacksonville, Florida",
      "St. Petersburg, Florida",
    ],
    Illinois: [
      "Chicago, Illinois",
      "Aurora, Illinois",
      "Naperville, Illinois",
      "Springfield, Illinois",
      "Rockford, Illinois",
    ],
    "New York": [
      "New York City, New York",
      "Buffalo, New York",
      "Rochester, New York",
      "Albany, New York",
      "Syracuse, New York",
    ],
    "North Carolina": [
      "Charlotte, North Carolina",
      "Raleigh, North Carolina",
      "Greensboro, North Carolina",
      "Durham, North Carolina",
      "Winston-Salem, North Carolina",
    ],
    Ohio: [
      "Columbus, Ohio",
      "Cleveland, Ohio",
      "Cincinnati, Ohio",
      "Toledo, Ohio",
      "Akron, Ohio",
    ],
    Pennsylvania: [
      "Philadelphia, Pennsylvania",
      "Pittsburgh, Pennsylvania",
      "Allentown, Pennsylvania",
      "Harrisburg, Pennsylvania",
      "Erie, Pennsylvania",
    ],
    Texas: [
      "Houston, Texas",
      "Dallas, Texas",
      "Austin, Texas",
      "San Antonio, Texas",
      "Fort Worth, Texas",
    ],
    remote:["Remote"]
  };
  