export const jobPlans = [
  {
    planId: 1,
    isBestValue: false,
    headline: "Resume rebuild & repositioning",
    price: "1",
    duration: "",
    setupFee: "",
    subHeading: "Best for VP to CxO level positioning - Tech and Non Tech",
    validity: "",
    detailsList: [
      "3 half hour coaching sessions with our founder - Ex-Google",
      "Deep consultation on positioning to stand out",
      "Interview coaching as required",
      "Resume reformat - ATS alignment",
      "Customization of resume to a particular industry or job",
      "Application strategy coaching",
      "Resume build portfolio available upon request",
    ],
  },
  {
    planId: 2,
    isBestValue: false,
    headline: "Mock interview / Interview prep",
    price: "500",
    duration: "",
    setupFee: "",
    subHeading:
      "Prep for Marketing, Product, Sales and VP/Director role interviews",
    validity: "",
    detailsList: [
      "Mock interview - At Google, I interviewed and hired 100's",
      "Two 45 minute sessions with Ashwin for targeted sessions",
      "Real time feedback",
      "Framing, confidence, empathy, value communication",
    ],
  },
  {
    planId: 3,
    isBestValue: false,
    headline: "Resume Build (Mid to Senior)",
    price: "350",
    duration: "",
    setupFee: "+$25 Setup fee",
    subHeading: "Best for mgr level to director positioning, Tech or Non Tech",
    validity: "Valid for one month",
    detailsList: [
      "Two, 30 min sessions with our resume coach",
      "Resume fit for the ATS & the human eye",
      "Linkedin Optimization Tips",
      "Interview prep and career story",
    ],
  },
  {
    planId: 4,
    isBestValue: false,
    headline: "Coaching sessions",
    price: "150",
    duration: "",
    setupFee: "",
    subHeading:
      "45 minute coaching sessions on application strategy, interview prep, offer negotiations or resume",
    validity: "Valid for 4 weeks",
    detailsList: [
      "With our Founder and CEO",
      "Resume positioning - how to best amplify for your strengths",
      "Offer negotiation - avg. salary data and negotiation strategy",
      "Interview prep - targeted prep for interview success",
    ],
  },
  {
    planId: 5,
    isBestValue: false,
    headline: "Advanced",
    price: "150",
    duration: "Every week",
    setupFee: "",
    subHeading: "Customized resumes for every application",
    validity: "",
    detailsList: [
      "Customized resumes (ATS optimized, Custom resume summary)",
      "Up to 25 job applications / week",
      "Dedicated analyst",
    ],
  },
  {
    planId: 6,
    isBestValue: true,
    headline: "Plus",
    price: "100",
    duration: "Every week",
    setupFee: "",
    subHeading: "Everything in Starter + More Applications",
    validity: "",
    detailsList: [
      "Everything in Starter",
      "Up to 75 Job Applications / week",
      "Job targeting complexity - Medium (3-6 job titles)",
      "Analyst support (8 hour turnaround)",
      "Interview monitoring & alerts",
    ],
  },
  {
    planId: 7,
    isBestValue: false,
    headline: "Starter",
    price: "50",
    duration: "Every week",
    setupFee: "+$25 Setup fee (Refunded on cancel <5 days)",
    subHeading: "Basic job application package",
    validity: "",
    detailsList: [
      "Initial consultation",
      "Up to 50 applications / week",
      "Custom Application Tracker",
      "Analyst support",
      "Job targeting complexity - Low (1-3 job titles)",
    ],
  },
  {
    planId: 8,
    isBestValue: false,
    headline: "January Promo Plan",
    price: "30",
    duration: "Every week",
    setupFee: "",
    subHeading:
      "Ideal for trying out the service with a low but targeted application volume",
    validity: "",
    detailsList: [
      "Up to 15 applications per week",
      "Dedicated human analyst with live support",
      "AI and human-based job matching and curation for targeting",
      "Customized application tracker",
      "10% discount on all Mobius services",
      "Daily application updates",
    ],
  },
  {
    planId: 9,
    isBestValue: false,
    headline: "Search and Curation",
    price: "15",
    duration: "Every week",
    setupFee: "+$20 Onboarding and intake fee",
    subHeading:
      "Our team will find the jobs that match your profile just right",
    validity: "Valid for 4 weeks",
    detailsList: [
      "Personalized application tracker",
      "Up to 5 job titles within search",
      "Dedicated human analyst to support your search",
      "Application tracker updated every 48 hrs with new jobs",
      "Intake and onboarding with our job analytics team",
      "AI and human-based filtering of jobs",
    ],
  },
  {
    planId: 10,
    isBestValue: false,
    headline: "One Time - Applications Add On (50)",
    price: "80",
    duration: "",
    setupFee: "",
    subHeading: "50 additional applications in a one week period",
    validity: "Valid for one week",
    detailsList: ["Add more application volume to your plan"],
  },
  {
    planId: 11,
    isBestValue: false,
    headline: "Hiring Manager Connect Database",
    price: "250",
    duration: "",
    setupFee: "",
    subHeading: "Database of hiring manager & recruiter contacts",
    validity: "",
    detailsList: [
      "Custom targeting criteria (job title, industry, location, etc.)",
      "500+ emails & LinkedIn URLs",
      "Live analyst support",
      "30+ attributes in contact database",
    ],
  },
  {
    planId: 12,
    isBestValue: false,
    headline: "ATS Resume Reformatting & Customization",
    price: "100",
    duration: "",
    setupFee: "",
    subHeading:
      "Basic resume package - reformat & basic cleanup/customization to get your resume conversion rate up",
    validity: "Valid for one month",
    detailsList: [
      "Dedicated analyst",
      "Full reformat to our proven ATS-friendly resume template",
      "Resume portfolio available on request",
      "Minor customizations to have a more crisp positioning",
    ],
  },
];
